# Generated by Django 6.0.6 on 2026-06-11 17:36

import movies.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', movies.models.CustomUserManager()),
            ],
        ),
    ]
